version: "3"

services:
  api:
    build:
      context: ./api
    ports:
      - '3001:3001'
    env_file:
      - .env
    networks:
      - docker-service
    depends_on: 
      - mariadb
      - ipfs
      - front-end

  front-end:
    build:
      context: ./client
    ports:
      - '80:3000'

  mariadb:
    image: mariadb
    ports:
      - '3306:3306'
    env_file:
      - .env
    networks:
      - docker-service
    volumes:
      - maria-data:/data/db
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  ipfs:
    image: ipfs/go-ipfs
    ports:
     - "4001:4001" 
     - "5001:5001"
     - "8080:8080"
    volumes:
      - ipfs-data:/data/ipfs

networks:
  docker-service:

volumes:
  maria-data:
  ipfs-data: