version: "3"

services:
  node:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment: 
      MYSQL_HOST: mariadb
    networks:
      - docker-service
    depends_on: 
      - mariadb

  mariadb:
    image: mariadb
    ports:
      - '3306:3306'
    env_file:
      - .env
    networks:
      - docker-service
    volumes:
      - maria-data:/data/db
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  
  ipfs:
    image: ipfs/go-ipfs
    ports:
     - "4001:4001" 
     - "5001:5001"
     - "8080:8080"
    volumes:
      - ipfs-data:/data/ipfs

networks:
  docker-service:

volumes:
  maria-data:
  ipfs-data: